### PR TITLE
refactor: optimise parser for performance

### LINKED ISSUE #20: Idea to improve performance of parsing by ~3x
First of all, thanks for all the hard work, this library has been instrumental for our use at @6fold and we truly appreciate that.

Recently we underwent a lot of performance profiling and optimising of some of our core code, during which we noticed that parsing dates is taking quite a lot of CPU cycles. After some experimentation, we ended up with our own parser that is about 3x as fast as the parser in this package.

We would love to contribute this back (we kept the test suite the same, so the two should be functionally equivalent), what is the preferred way, should we just open a PR against this package with the re-write?

We are asking as the alternative could also be to contribute a PR to upstream (in our case https://github.com/brianc/node-pg-types) with a PR to swap out the date parsing library.

EDIT: Here's a link to our package that contains the faster implementation - https://github.com/6fold/fast-postgres-date-parser

### PR DESCRIPTION
**Pull request by henrinormak**
Closes #20

It is not verbatim copy of the TS version of the parser we wrote, as I didn't want to convert this package to typescript (let me know if you think that's still valid and OK to do).

It also handles infinity slightly differently (we chose to go with always returning a Date object, instead of returning either date or number) than the package mentioned in the issue.

The performance gains should still be there though.

### CODE REVIEW

**Comment by bendrucker** [comment]
Thanks, will have a look at this soon!

> I didn't want to convert this package to typescript (let me know if you think that's still valid and OK to do).

Appreciated, I'm happy to have typings included but I'm more hesitant to take on the burden of having to transpile.

**Comment by henrinormak** [comment]
Have you had time to check this out? Regards TS, I think it then makes sense to just skip typing this package, if there is a need, a package can be added to DefinitelyTyped.

**Comment by bendrucker** [comment]
Sorry not yet but should get to it this week

**Comment by bendrucker** [comment]
Published as `2.0.1`, thanks again!

**Pull request merged**
